name: 'Packages Split'

on:
    push:
        branches:
            - main
        tags:
            - '*'

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    USER_NAME: "samueljtaylor"
    USER_EMAIL: "15961687+samueljtaylor@users.noreply.github.com"

jobs:
    packages_split:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                directory: ["arrays","common","composer","filesystem","flags","json"]
        steps:
            -   uses: actions/checkout@v2

            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@2.1"
                with:
                    package_directory: 'src/${{ matrix.directory }}'
                    repository_organization: '${{ github.repository_owner }}'
                    repository_name: 'tool-${{ matrix.directory }}'
                    user_name: '${{ env.USER_NAME }}'
                    user_email: '${{ env.USER_EMAIL }}'

            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@2.1"
                with:
                    tag: ${GITHUB_REF#refs/tags/}
                    package_directory: 'src/${{ matrix.directory }}'
                    repository_organization: '${{ github.repository_owner }}'
                    repository_name: 'tool-${{ matrix.directory }}'
                    user_name: '${{ env.USER_NAME }}'
                    user_email: '${{ env.USER_EMAIL }}'
